force-app/main/default/objects/Account_Coupon__c/Account_Coupon__c.object-meta.xml
<CustomObject>
    <label>Account Coupon</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Account Coupon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Coupons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Coupon__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Coupons</relationshipLabel>
    <relationshipName>Account_Coupons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Coupon__c/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <label>Coupon</label>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Account Coupons</relationshipLabel>
    <relationshipName>Account_Coupons</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Coupon__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Account Coupons</relationshipLabel>
    <relationshipName>Account_Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateAccountCouponsJob.cls
public without sharing class CreateAccountCouponsJob implements Database.Batchable<sObject>, Schedulable{
    private Map<String, Coupon__c> couponByName = CouponService.getCouponByName();    

    public Database.QueryLocator start(Database.BatchableContext context) {       
        return Database.getQueryLocator([SELECT Id, Customer_Status__c FROM Account WHERE Customer_Status__c != null]);
    }

    public void execute(Database.BatchableContext context, List<Account> scope) {
        List<Product2> newProducts = ProductSelector.getProductsByCouponCreated(false);
        List<Account_Coupon__c> accCouponsToInsert = new List<Account_Coupon__c>();
        for(Account acc : scope){          
            for(Product2 prod : newProducts){
               Account_Coupon__c accCoupon = new Account_Coupon__c(Account__c = acc.Id, Coupon__c = couponByName.get(acc.Customer_Status__c).Id, Product__c = prod.Id);
               accCouponsToInsert.add(accCoupon);
               prod.Coupon_Created__c = true;
            }        
        }
        insert accCouponsToInsert;   
        update newProducts;    
    }

    public void finish(Database.BatchableContext context) {
        
    }

    public void execute(SchedulableContext context) {
        Database.executeBatch(new CreateAccountCouponsJob());
    }
}