force-app/main/default/objects/Account_Coupon__c/Account_Coupon__c.object-meta.xml
<CustomObject>
    <label>Account Coupon</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Account Coupon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Coupons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Coupon__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Coupons</relationshipLabel>
    <relationshipName>Account_Coupons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AccountSelector.cls
public inherited sharing class AccountSelector {
    
    /**
     * @description - retrieves accounts
     * @param accIDs - Account Ids
     * @return - List<Account>()
     */
    public static List<Account> getAccountsByIDs(List<Id> accIDs){
        if(accIDs == null || accIDs.isEmpty()){
            return new List<Account>();
        }
         return [
            SELECT Id, Contact_Count__c, (SELECT Id FROM Contacts)
            FROM Account 
            WHERE Id 
            IN :accIDs
        ];
    }

    /**
     * @description - retrieves accounts
     * @param accountIds - account ids
     * @return - List<Account_Coupon__c>()
     */
    public static List<Account_Coupon__c> getAccountCoupons(List<Id> accountIds){
        return [SELECT Id FROM Account_Coupon__c WHERE Account__c IN :accountIds];
    }
}