force-app/main/default/objects/Security_Code_Mapping__mdt/Security_Code_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Security Code Mapping</label>
    <pluralLabel>Security Code Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Security_Code_Mapping__mdt/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
public with sharing class CaseTriggerHandler extends TriggerHandler{
    
    List<Case> newCases = Trigger.new;

    public override void beforeInsert(){
        processSecurityCode();
    }

    public override void beforeUpdate(){
        processSecurityCode();
    }
       
    public void processSecurityCode(){
        Map<String, Security_Code_Mapping__mdt> codeMappings = Security_Code_Mapping__mdt.getAll();        
        for(Case newCs : newCases){
            if(!codeMappings.containsKey(newCs.Security_Code__c)){
                newCs.addError('Security Code does not exist');
            }    
            else{
                newCs.State__c = codeMappings.get(newCs.Security_Code__c).State__c;
            }      
        }       
    }
}